# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wrlyyNIBWxvH5XGqZHqytXTcwLIkwTXN
"""

def sumArray(array): #Öncelikle fonksiyonu tanımladık.
  sum = 0 #İlk başta sum değeri sıfıra eşittir.
  for number in array: #Array'de bulunan her sayı için
    sum += number #Sayıların toplamını alıp sum'a atar.
  print(sum) #Döngü tamamladıktan sonra toplamını yazdırır.

sumArray([1, 2, 3, 4, 5]) #Örnek1
sumArray([5,-6,-9,4,30])  #Örnek2