# -*- coding: utf-8 -*-
"""Find Palindrome Alternative Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XkfxXRdZ8lSsjIohQBlwnZI1c9Q7W4sF
"""

string = "hello"
array = list(string)
is_palindrome = True
for i in range(len(array)):
  if (array[i] != array[-(i+1)]):
    is_palindrome = False
    break

if is_palindrome:
  print("palindrome")
else:
  print("not a palindrome")