# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XkfxXRdZ8lSsjIohQBlwnZI1c9Q7W4sF
"""

def findMax(Array): #Python'da fonksiyon oluştururken "#" işareti kullanılır.
      max_val = Array[0] #Array'in ilk değerini max_val'a atayalım.
      for num in Array:  #Şimdi bir tane for döngüsü yapalım.
        if num > max_val: #Eğer sayı, max_val'dan büyük ise
            max_val =num  #Sayıyı alıyoruz ve max_val'in içine atıyoruz.
      print(max_val) #Döngü bittikten sonra print yapıp yazdırıyoruz.


findMax([3, 7, 10, 9, 1]) #findMax fonksiyonunun örnek bir kullanımı