# -*- coding: utf-8 -*-
"""Reverse Words.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BjLEJBdEuMmcpsP3hs0lkL5xm6njp2Ra
"""

def reverseWords(string):
  reverse_string="" #Bunu boş bırak.
  for character in string:
    reverse_string = character + reverse_string #character önce yazınca oldu.
  print(reverse_string)

reverseWords("hello")

def reverseWords(string): #define function
  return string[::-1]

print(reverseWords("hello"))