# -*- coding: utf-8 -*-
"""Tekrar edeni bulma.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZkwKkLDr5Rit-3KNSiwlBxqEVaDOJFr
"""

def firstRepeatingChar(string):#We define the function here.
  array = list(string) #String'i parçalara ayıralım.
  for n in range(len(array) - 1): #For döngüsü kullanalım.
    if array[n] == array[n+1]: #Eğer aynı olanı bulursanız
      return array[n] #return the value n
  return None  # Return None if no repeating character is found

print(firstRepeatingChar("hello")) #example1
print(firstRepeatingChar("abcde")) #example2